### ISSUE TITLE
More doctest fixes

### ISSUE THREAD

**Issue by MarionBWeinzierl** [ImperialCollegeLondon/pyrealm#110]
If I run doctests. e.g. `poetry run python -m doctest pyrealm/pmodel/pmodel.py`, I get several of the following type of error messages:
> Failed example:
        np.round(mod_c4.gpp, 5)
    Expected:
        103.25886 
    Got:
        array([103.25886])

This is a similar issue as in #92

**Comment by davidorme** [comment]
I do not get this on `develop` - that test no longer uses `np.round`?

https://github.com/ImperialCollegeLondon/pyrealm/blob/develop/pyrealm/pmodel/pmodel.py#L340-L341

**Comment by MarionBWeinzierl** [comment]
Ah, I am on main!

--
Dr Marion Weinzierl
Senior Research Software Engineer
Institute of Computing for Climate Science (ICCS)
University of Cambridge
________________________________
