### ISSUE TITLE
Pip install tmodel issues in TTree class

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [ImperialCollegeLondon/pyrealm#117]
**Describe the bug**
When pip installing pyrealm on Windows 10 with pycharm in either python 3.7 or python 3.11, in tmodel.py  diameters is not included in the TTree class initialization. This is necessary to run the T model documentation example.

Furthermore, when pip installing, the constants folder is not downloaded either which is also necessary to run the T model examples.

**To Reproduce**
pip install Pyrealm 0.8.1 and attempt to run T model examples.

**Expected behavior**
Code completes with no errors i.e. exit code 0

**Comment by tztsai** [comment]
Does this bug still exist? I've run the code as follows and it did not produce any error.

<img width="786" alt="image" src="https://github.com/ImperialCollegeLondon/pyrealm/assets/34415979/0d6eccce-37ff-4b74-91ee-67b2e78f9065">
