### ISSUE TITLE
Add information about how to create the profiling call graph

### ISSUE THREAD

**Issue by MarionBWeinzierl** [ImperialCollegeLondon/pyrealm#145]
The information about profiling in CONTRIBUTING.md is missing the info how to create the call graph from #81 , see https://github.com/ImperialCollegeLondon/pyrealm/issues/81#issuecomment-1683632703 . The same comment also provides the command for the coverage report. Note that the command needs graphviz installed, which includes dot, which is the tool to convert the files to svg.

This information should be added to CONTRIBUTING.md.

**Comment by TZTsai** [comment]
Windows developers will need manually install graphviz. For example from releases at https://gitlab.com/graphviz/graphviz/-/releases.
