### ISSUE TITLE
Call graph is not generated in CI given the cmd option `--profile-svg` even though `graphviz` is installed.

### ISSUE THREAD

**Issue by tztsai** [ImperialCollegeLondon/pyrealm#152]
**Describe the bug**
<img width="782" alt="image" src="https://github.com/ImperialCollegeLondon/pyrealm/assets/34415979/f5ed0d0d-b5a2-4497-9376-d9fdc02596d8">

**Comment by surbhigoel77** [comment]
`graphviz` only helps to render the generated xml/ svg file to a graph. If the file is not generated, it could be something else.

**Comment by tztsai** [comment]
I've found that the issue is because `poetry` only installed the python package of `graphviz`. In order to generate the SVG file, we must run `sudo apt-get install graphviz` as well (for ubuntu). I have added this line in the CI file in my PR #149.
