### ISSUE TITLE
Add `splash` to profiling suite.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#166]
**Is your feature request related to a problem? Please describe.**
With the merging of #69, it would be good to add the SPLASH module to the profiling suite so we can monitor it for performance regression and choke points.

**Describe the solution you'd like**
Take the example analysis in `docs/sources/users/splash.md` and convert it into a profiling test. That dataset isn't particularly big, so we might want to consider something with a heavier load at some point, but it should be fine for now.

**Comment by tztsai** [comment]
I'm using the `splash_test_grid_nw_us.nc` dataset to profile `SplashModel` as in the example in `splash.md`. I wonder if a single function calling `estimate_initial_soil_moisture` followed by `calculate_soil_moisture` for the whole time series suffice to measure the runtime performance of the whole `Splash` module.
