### ISSUE TITLE
Regression test of `splash.evap` does not pass

### ISSUE THREAD

**Issue by tztsai** [ImperialCollegeLondon/pyrealm#173]
After the hot fix in #171, the assertion in `tests/regression/test_evap.py` fails.

**Comment by davidorme** [comment]
Good catch - that is odd, given that the higher level test of the whole SPLASH process passes.

**Comment by davidorme** [comment]
OK - got it. The AET component of the water balance equation is the evapotranspiration loss calculated from the previous day's soil moisture. Need to prepend the spun up initial wn and drop the last day on the inputs to `estimate_aet`.
