### ISSUE TITLE
Some tests produce out of bound errors

### ISSUE THREAD

**Issue by tztsai** [ImperialCollegeLondon/pyrealm#174]
I changed the function `bounds_checker` from producing a warning to raising an error when the input contains out-of-bound values. After that, however, some of the existing tests cannot pass.

![image](https://github.com/ImperialCollegeLondon/pyrealm/assets/34415979/ec10cbf3-b709-46a8-a532-ca6030223f6b)

**Comment by davidorme** [comment]
@tztsai Can you link this into other issues or PRs please - there's no context to find out where this bug appeared or why it was closed.

**Comment by tztsai** [comment]
These errors were just because those failing tests expect `UserWarning` instead of `ValueError`. Therefore I think there's no bug, so I closed this issue.

**Comment by davidorme** [comment]
Thanks - which PR was this in?
