### ISSUE TITLE
Update github actions.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#178]
**Describe the bug**
The CI on GitHub is now reporting deprecation warnings about actions that use Node 16. Most (all?) actions we use now seem to have rolled out Node 20 versions which we can drop in.

**To Reproduce**
Look at reports from github actions.

**Comment by tztsai** [comment]
![image](https://github.com/ImperialCollegeLondon/pyrealm/assets/34415979/50ea7ef3-f30c-4c7a-9d02-f68e5ff1a026)

The latest versions of the actions involved in this issue are `checkout@v4` and `setup-python@v5`. I've submitted a PR to check if the updated versions will solve the issue.
