### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#23]
The bulk of the unit testing at the moment is validation of the `pyrealm` predictions against the predictions of other implementations. The test suites need more simple tests checking that the basic classes and functions work as intended - clearer checking of failure modes.

**Comment by MarionBWeinzierl** [comment]
Start to add tests when errors come up, add unit tests

**Comment by MarionBWeinzierl** [comment]
Split tests into unit tests vs regression/integration tests?

**Comment by davidorme** [comment]
Closing as done.
