### ISSUE TITLE
Develop pyrealm.core.solar function radiation calc library

### ISSUE THREAD

**Issue by j-emberton** [ImperialCollegeLondon/pyrealm#236]
Proposal to breakout individual solar radiation calc functions from `pyrealm.splash.solar` and make these available in `pyrealm.core.solar`

**Alternatives**
Alternative would be to try and find an existing Python library to provide similar functionality and then write custom functions for any missing features such as calculation of ppfd and calculation of radiation for sub-daily intervals..
Seeing as we already have much of the code we need in `Pyrealm`, we might as well reuse it.

**Additional context**
This is in support of implementing the two-leaf canopy model

**Comment by davidorme** [comment]
In particular, the existing code in `pyrealm` handles array inputs, where other libraries tend to be more focussed on single locations.
