### ISSUE TITLE
PR Checker Github actions hanging after approval

### ISSUE THREAD

**Issue by AmyOctoCat** [ImperialCollegeLondon/pyrealm#241]
**Describe the bug**
Once a PR has been approved in Github and the profiling has been run, the other PR checks are hanging in a pending state. This may be because the commit message for the autocommit contains [skip actions], but it may also be to do with the fact that an action (the profiling) is triggering the other actions. Will open up a branch to see if just modifying the commit message fixes it.

**To Reproduce**

1. Open a PR
2. Have it approved
3. Wait for checks to run

**Expected behavior**
Checks hang in a 'Waiting to execute' state.

**Comment by davidorme** [comment]
Closed as we have stopped the auto-profiling that was causing this issue
