### ISSUE TITLE
Failing tests for python 3.11 on MacOS

### ISSUE THREAD

**Issue by AmyOctoCat** [ImperialCollegeLondon/pyrealm#274]
**Describe the bug**
Tests are currently failing on the `main` and `develop` branches.

**To Reproduce**
1. Checkout the latest version of `main` (same happens on `develop`)
2. Run pytest using: `poetry run python -m pytest`
4. The following tests fail: FAILED pyrealm/core/utilities.py::pyrealm.core.utilities
FAILED pyrealm/core/utilities.py::pyrealm.core.utilities.bounds_mask
FAILED pyrealm/core/water.py::pyrealm.core.water.calc_density_h2o
FAILED pyrealm/core/water.py::pyrealm.core.water.calc_density_h2o_chen
FAILED pyrealm/core/water.py::pyrealm.core.water.calc_density_h2o_fisher
FAILED pyrealm/core/water.py::pyrealm.core.water.calc_viscosity_h2o
FAILED pyrealm/core/water.py::pyrealm.core.water.calc_viscosity_h2o_matrix
FAILED pyrealm/pmodel/functions.py::pyrealm.pmodel.functions.calc_co2_to_ca
FAILED pyrealm/pmodel/functions.py::pyrealm.pmodel.functions.calc_ftemp_arrh
FAILED pyrealm/pmodel/functions.py::pyrealm.pmodel.functions.calc_ftemp_inst_rd
FAILED pyrealm/pmodel/functions.py::pyrealm.pmodel.functions.calc_ftemp_inst_vcmax
FAILED pyrealm/pmodel/functions.py::pyrealm.pmodel.functions.calc_ftemp_kphio
FAILED pyrealm/pmodel/functions.py::pyrealm.pmodel.functions.calc_kmm
FAILED pyrealm/pmodel/functions.py::pyrealm.pmodel.functions.calc_ns_star

**Expected behavior**
All tests to pass

**Screenshots**
<img width="1487" alt="Screenshot 2024-08-23 at 15 26 24" src="https://github.com/user-attachments/assets/985547ad-8e9c-41dd-8e28-bb27bb793e75">

**Desktop (please complete the following information):**

- OS: MacOS with M2 chip
- Version 14.5 (23F79)
- 
poetry run python --version
Python 3.11.0

**Comment by AmyOctoCat** [comment]
This was a local poetry setup error - I had not run a recent enough install. Apologies for any confusion!

**Comment by davidorme** [comment]
I had exactly the same thing 😄 "Fixed" them all on another branch and then had to revert them.
