### ISSUE TITLE
Potential Discrepancy in Yield Factor Value in tmodel_const.py

### ISSUE THREAD

**Issue by Syuizen** [ImperialCollegeLondon/pyrealm#281]
# Description

Hello,

While reviewing the [`tmodel_const.py`](https://github.com/ImperialCollegeLondon/pyrealm/blob/main/pyrealm/constants/tmodel_const.py) file, I noticed that the `yld` (Yield Factor) is currently set to `0.17`. However, based on the reference paper (Table 1 of [*Li et al., 2014*](https://bg.copernicus.org/articles/11/6711/2014/)), the yield factor should be `0.6`.

Here is the specific line in question:
```python
yld: float = 0.17  # y, Yield_factor (-)
"""Yield_factor (:math:`y`, 0.17, -)"""
```

I’m not entirely sure if this is an intentional adjustment or a possible typo, but I thought it would be helpful to raise it here for clarification.

Thank you in advance for looking into this. I really appreciate all the hard work that goes into creating this project!

Best,
Yiran

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)

### Key checklist
N/A

### Further checks
N/A

**Comment by davidorme** [comment]
Yup - that is indeed a typo from the table, duplicating the value of the default "ratio of fine-root mass to foliage area". Good spot.
