### ISSUE TITLE
Upgrade "uploadartifact" from v3 to v4

### ISSUE THREAD

**Issue by MarionBWeinzierl** [ImperialCollegeLondon/pyrealm#353]
This affects `docs_build` in our CI Actions:

![Image](https://github.com/user-attachments/assets/a39f4433-db42-4e28-8349-0827de1962ef)

Hopefully the differences/breaking changes listed at https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes should not affect us.

**Comment by davidorme** [comment]
None of the breaking changes look like they apply. The usage here uploads a single ZIP of the `sphinx` `build` contents if the build process fails, mostly so we can see the logs if something goes wrong _only_ on the runner. Mostly doc build failures occur locally as well.
