### ISSUE TITLE
Add a statement of need to provide context for the software use. Add to readme and documentation. This could include example use cases.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#55]

**Comment by MarionBWeinzierl** [comment]
I think this has been mostly achieved through work on the readme (see #91 ).

If there are no additional use cases or context information to be added we can close this.

**Comment by davidorme** [comment]
I agree, @MarionBWeinzierl - also overlaps quite a lot with #98 which also contains a similar statement.
