### ISSUE TITLE
Check requirements and ensure that these are consistent between pyproject.toml and poetry.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#56]
Intention is to move over to entirely do this within poetry. There are a few dependencies in the environment that are not required as a result of tinkering with libraries.

**Comment by MarionBWeinzierl** [comment]
@davidorme , when you say "tinkering with libraries", do you mean you have changed/updated pyproject.toml? 

If we are confident that pyproject.toml provides the up-to-date versions of the libraries that we want, then the easiest way would be deleting poetry.lock, rerunning poetry with pyproject.toml, and committing the new poetry.lock file.

**Comment by davidorme** [comment]
I think the issue was that there were imports in the code for libraries that then weren't used - `bottleneck` was one. When I updated the QA tools, I think that cleared all those out in the code, but I'm not sure I updated `pyproject.toml`. So, we're looking for libraries in `pyproject.toml` that don't currently get used.

I think this is just `Bottleneck` now. Possibly `netCDF4` but that might be an optional backend to `xarray`. Might be worth commenting the lines in `pyproject.toml`!

**Comment by MarionBWeinzierl** [comment]
Should we get rid of [requirements.txt](https://github.com/ImperialCollegeLondon/pyrealm/blob/develop/requirements.txt) ?

**Comment by davidorme** [comment]
Yes - definitely outdated and redundant.

**Comment by MarionBWeinzierl** [comment]
Hm, I tried commenting out those lines and the tests still run through fine. I also tried commenting out a couple of other lines, and for surprisingly many (including, for example, scipy) the tests still go through fine - do you think that is due to intertwined cross-dependencies which get resolved by poetry, or the tests not covering enough?

**Comment by davidorme** [comment]
I strongly suspect it is the cross-dependencies. The tests should have decent coverage. At the moment they nearly all revolve around testing the `pyrealm` implementation against benchmark outputs from other implementations, but running those large scale comparisons should call most if not all of the internals.

**Comment by MarionBWeinzierl** [comment]
OK, NetCDF4 seems to actually be used in the docs somewhere, see https://github.com/ImperialCollegeLondon/pyrealm/actions/runs/6246641204

**Comment by davidorme** [comment]
I've checked the doc build logs in the run artefacts and yes:

> found the following matches with the input file in xarray's IO backends: ['netcdf4', 'h5netcdf']. But their dependencies may not be installed,

Looks like the `xarray` developers have gone with a very minimal set of dependencies (https://xarray.pydata.org/en/v2023.08.0/getting-started-guide/installing.html) so we either need to retain NetCDF4 or use  `xarray[io]` for their more extended recommended set of I/O dependencies. Probably fine with NetCDF4 alone for now.
