### ISSUE TITLE
Move embedded constants in the code into the constants file.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#59]
There are a small number of places where constants are hard coded e.g. ‘kphio’ value in ‘pmodel’. It is suggested that these could be moved into the constants file (as there is one already).

**Comment by mondus** [comment]
Constants file need a root and branch review. E.g. P models constants file includes a bunch of things that are in other shared models (e.g. splash). Suggests that constants file needs a refactor and as such this issue might be a moving target...

**Comment by davidorme** [comment]
Particularly with the incoming functionality in the WIP PR #69 , which will probably result in a new `core` module containing various shared functions (`core.hygro`, `core.solar` etc, each of which is likely to have a smaller distinct constant dataclass).

**Comment by MarionBWeinzierl** [comment]
kphio is not a constant, but a tuning parameter. A number of other issues tackle the other constants (#76)
