### ISSUE TITLE
Add links to documentation on main repo readme (and under GitHub settings).

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#61]

**Comment by MarionBWeinzierl** [comment]
I added the links to the Readme on the [`71-improve-readme`](https://github.com/ImperialCollegeLondon/pyrealm/tree/71-improve-readme) branch, but I have not the necessary rights to add them to the repository "About" settings. @davidorme , are you able to do that?

**Comment by davidorme** [comment]
Done
