### ISSUE TITLE
Add a CONTRIBUTING.md and describe the git flow workflow that is used.

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#65]

**Comment by MarionBWeinzierl** [comment]
As a first step, we could move what is documented under *Release Process* in the ReadMe.

 @mondus @a-smith-github , do you think it needs to be more extensive?

**Comment by davidorme** [comment]
I think most of the current `README.md` is developer-facing and should probably be in `CONTRIBUTING.md`. Then the `README.md` can just be a short overview and description of what the package does. The examples of use might go in that too, but could go to the website? We can handle this on the `[64-add-licence-to-repository](https://github.com/ImperialCollegeLondon/pyrealm/tree/64-add-licence-to-repository)` branch?

Incidentally - is there a particular scheme to the branch labelling that I should follow here?

**Comment by davidorme** [comment]
The `README.md` is also used as the landing page on PyPi, so needs to be user focussed and short.
