### ISSUE TITLE
NA handling in subdaily models etc

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#70]
**Describe the bug**

The main `PModel` code is not bothered about `np.nan` values in inputs - there will be a gap in predictions but it all works. However, the `memory_effect` and `fill_daily_to_subdaily` methods in `FastSlowPModel` iterate over time series and get derailed by missing values.

There are various ways this could be handled - and these are most easily dealt with by removing `np.nan` values before fitting models. Then users can decide what to do rather than having baked in approaches. However, the methods should then look for `np.nan` in inputs (perhaps excluding leading and trailing `np.nan`) and raise a `ValueError`.

**Expected behavior**

* FastSlowPModel fails with missing data and reports the need to fill gaps in inputs.
* Docs for the approach make this clear and point to useful solutions like `xarray.ffill` or `scipy.interpolate` etc.

**Comment by davidorme** [comment]
This is partly resolved by #78 closing #77, but this doesn't document the expectation that forcing variables should not have missing data.

**Comment by MarionBWeinzierl** [comment]
Could use None if using xarrays, but it's slow.

Helper function to check about NAs in the functions that care about NAs, but not in others?

Use a specific error check?

**Comment by mondus** [comment]
Good description of this here: https://www.residentmar.io/2016/06/12/null-and-missing-data-python.html

**Comment by davidorme** [comment]
This is now covered by #78 and also the more extensive documentation and handling of missing data arising from allowing partial start and end days with the subdaily model in #194.
