### ISSUE TITLE
Improve ReadMe

### ISSUE THREAD

**Issue by MarionBWeinzierl** [ImperialCollegeLondon/pyrealm#71]
From the Readme alone, it is almost impossible to get the code running, and there are also a couple of loose ends.

Suggestions:

1. Add the links to documentation (first paragraph as well as online documentation paragraph), build status (CI paragraph) and admin side (Check the documentation builds paragraph).
2. Add explanation what the code actually does (see also #55 ), how it is run (standalone? coupled? what are the inputs and outputs?), and, if applicable, relevant papers
3. Add/improve instructions which can be copied and pasted into the command line for running the tests and the documentation. These can basically be taken from https://github.com/davidorme/pyrealm/blob/develop/.github/workflows/pyrealm_ci.yaml 
4. Add instructions on how to run a minimal example of the code

#57 and #61 can also be dealt with in this issue.

**Comment by davidorme** [comment]
Yup - it is outdated and also very much aimed at developer information rather than users.

**Comment by MarionBWeinzierl** [comment]
I started working on the Readme here: https://github.com/ImperialCollegeLondon/pyrealm/blob/71-improve-readme/README.md .

@davidorme, there are some TODOs (I put them directly into the Readme file) which I need your help with. Could you please have a look at them? Happy to have a chat at some point if it is easier to sort them out that way.
