### ISSUE TITLE
Profiling PyRealm To Identify Performance Bottlenecks & Regressions

### ISSUE THREAD

**Issue by a-smith-github** [ImperialCollegeLondon/pyrealm#81]
**Is your feature request related to a problem? Please describe.**
As discussed, we should investigate profiling the code-base for the p-model to identify bottlenecks and identify areas where we can improve the performance. There is scope to convert this into an automated process to run alongside other testing or create a trigger that causes a failure if a regression is introduced (if desired). 

**Describe the solution you'd like**
I'll use this issue to track any profiling work and link a pull request against it if we decide to include profiling as a standard action on push to branches in this repository. 

**Describe alternatives you've considered**
We could use a pytest plugin like pytest-profiling to perform the dynamic profiling as part of the CI/test suites. This runs cProfile under the hood plus a few other tools to generate heat graphs etc. but we could limit the scope of any automated process to only using cProfile and responding to the output data. Other tools like PyInstrument exist for statistical profiling. 

For benchmarking we could use the profiling tools, however this may be heavy handed and something like tesit or pytest-benchmarking or something directly accessible from GitHub Actions may be more suitable. This could be worth tracking as a separate issue. 

**Additional context**
We discussed using a dataset that was >1GB in size as a real-world example. For the time being, we could use the data in the example and scale it up as needed.

**Comment by a-smith-github** [comment]
Currently Investigating

**Comment by a-smith-github** [comment]
Note: The description previously discussed a file I/O issue which accounted for a significant amount of the time. This is a pre-processing step outside the scope of the P-Model / PyRealm.

**Comment by mondus** [comment]
Question for @davidorme. Do you foresee the profiling/benchmarking living in the PyRealm repo or should we create an example in a separate repo using the pyRealm package?

**Comment by davidorme** [comment]
I'm not sure - I think there's an argument for a separate repo to keep `pyrealm` simple - but this would be code that is _purely_ intended to work with the `pyrealm` codebase.

Would it make sense to add another package with the `pyrealm` repo and `prproject.toml`. I've already got a small `pyrealm_build_data` package, so adding a `pyrealm_profiling` package in the repo might work well. That makes it easy to use `importlib` to get at paths and the like.

One thing is how we handle datafiles. If the profiling requires large data files that can't simply be generated procedurally when needed - for example if we use something like those netCDF files I posted - then I guess we end up having to use `git-lfs` or similar?

**Comment by a-smith-github** [comment]
An update on progress. I've taken one of the examples from the read the docs and created a new test for profiling which uses the 1.77GB dataset ("inputs_data_24.25.nc") David provided. Running "poetry run pytest tests/pmodel/test_profiling.py --profile-svg" which leverages the pytest-profiling plugin, it produces this call graph

![combined](https://github.com/ImperialCollegeLondon/pyrealm/assets/48871394/09335e49-8740-4398-80f4-049775b69758)

And if I run "poetry run pytest --cov=pyrealm/pmodel/ tests/pmodel/test_profiling.py" --- which is just to qualify the profiling result, not PyRealm ---- the coverage statistics for that test were:

Coverage report: 53%
coverage.py v7.3.0, created at 2023-08-18 10:18 +0100

Module	statements	missing	excluded	coverage
pyrealm/__init__.py	14	2	0	86%
pyrealm/constants/__init__.py	6	0	0	100%
pyrealm/constants/base.py	17	7	0	59%
pyrealm/constants/competition_const.py	16	0	0	100%
pyrealm/constants/hygro_const.py	22	5	0	77%
pyrealm/constants/isotope_const.py	26	0	0	100%
pyrealm/constants/pmodel_const.py	108	0	0	100%
pyrealm/constants/tmodel_const.py	32	0	0	100%
pyrealm/hygro.py	21	12	0	43%
pyrealm/pmodel/__init__.py	6	0	0	100%
pyrealm/pmodel/competition.py	50	39	0	22%
pyrealm/pmodel/fast_slow_scaler.py	125	112	0	10%
pyrealm/pmodel/functions.py	88	19	0	78%
pyrealm/pmodel/isotopes.py	48	36	0	25%
pyrealm/pmodel/pmodel.py	298	83	0	72%
pyrealm/pmodel/subdaily.py	123	112	0	9%
pyrealm/tmodel.py	114	114	0	0%
pyrealm/utilities.py	76	24	0	68%
Total	1190	565	0	53%
coverage.py v7.3.0, created at 2023-08-18 10:18 +0100

**Comment by mondus** [comment]
@a-smith-github Could you try advice in https://stackoverflow.com/questions/9000164/how-to-check-blas-lapack-linkage-in-numpy-and-scipy to find out what backend your `numpy` is using?

**Comment by MarionBWeinzierl** [comment]
@a-smith-github @davidorme : From the dev meeting: Find example with better code coverage to make sure we're not missing something.
