### ISSUE TITLE
Weekly Pre-commit auto-update fails

### ISSUE THREAD

**Issue by a-smith-github** [ImperialCollegeLondon/pyrealm#83]
**Describe the bug**
Error thrown in the CI on scheduled jobs. Not caught by submission/PR jobs. 

Reported by mypy & markdownlint

Should be investigated. Use Issue to track. 

**Syndrome**

Run browniebroke/pre-commit-autoupdate-action@main
Run pip install pre-commit
Collecting pre-commit
  Obtaining dependency information for pre-commit from https://files.pythonhosted.org/packages/e3/b7/1d145c[9](https://github.com/ImperialCollegeLondon/pyrealm/actions/runs/5779472488/job/15661796146#step:4:10)85d8be9729672a45b8b8113030ad60dff45dec592efc4e5f5897a/pre_commit-3.3.3-py2.py3-none-any.whl.metadata
  Downloading pre_commit-3.3.3-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting cfgv>=2.0.0 (from pre-commit)
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting identify>=1.0.0 (from pre-commit)
  Obtaining dependency information for identify>=1.0.0 from https://files.pythonhosted.org/packages/63/53/6e728e41c2fc620f020cff3e9c8c36f24a1b9be5e983f1bc3778e8609a34/identify-2.5.26-py2.py3-none-any.whl.metadata
  Downloading identify-2.5.26-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting nodeenv>=0.11.1 (from pre-commit)
  Obtaining dependency information for nodeenv>=0.11.1 from https://files.pythonhosted.org/packages/1a/e6/6d2ead760a9ddb35e65740fd5a57e46aadd7b0c49861ab24f94812797a1c/nodeenv-1.8.0-py2.py3-none-any.whl.metadata
  Downloading nodeenv-1.8.0-py2.py3-none-any.whl.metadata (21 kB)
Collecting pyyaml>=5.1 (from pre-commit)
  Obtaining dependency information for pyyaml>=5.1 from https://files.pythonhosted.org/packages/7d/39/472f2554a0f1e825bd7c5afc11c817cd7a2f3657460f7159f691fbb37c51/PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting virtualenv>=20.10.0 (from pre-commit)
  Obtaining dependency information for virtualenv>=20.10.0 from https://files.pythonhosted.org/packages/14/[19](https://github.com/ImperialCollegeLondon/pyrealm/actions/runs/5779472488/job/15661796146#step:4:21)/e266f07cf55155d5f45170bbe08c486d8a9a9ae17bc8983acb1c019a8dd4/virtualenv-[20](https://github.com/ImperialCollegeLondon/pyrealm/actions/runs/5779472488/job/15661796146#step:4:22).24.2-py3-none-any.whl.metadata
  Downloading virtualenv-20.24.2-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages (from nodeenv>=0.11.1->pre-commit) (58.1.0)
Collecting distlib<1,>=0.3.7 (from virtualenv>=20.10.0->pre-commit)
  Obtaining dependency information for distlib<1,>=0.3.7 from https://files.pythonhosted.org/packages/43/a0/9ba967fdbd55293bacfc1507f58e316f740a3b231fc00e3d86dc39bc185a/distlib-0.3.7-py2.py3-none-any.whl.metadata
  Downloading distlib-0.3.7-py2.py3-none-any.whl.metadata (5.1 kB)
Collecting filelock<4,>=3.12.2 (from virtualenv>=20.10.0->pre-commit)
  Obtaining dependency information for filelock<4,>=3.12.2 from https://files.pythonhosted.org/packages/00/45/ec3407adf6f6b5bf867a4462b2b0af27597a26bd3cd6e2534cb6ab029938/filelock-3.12.2-py3-none-any.whl.metadata
  Downloading filelock-3.12.2-py3-none-any.whl.metadata (2.7 kB)
Collecting platformdirs<4,>=3.9.1 (from virtualenv>=20.10.0->pre-commit)
  Obtaining dependency information for platformdirs<4,>=3.9.1 from https://files.pythonhosted.org/packages/14/51/fe5a0d6ea589f0d4a1b97824fb518962ad48b27cd346dcdfa2405187997a/platformdirs-3.10.0-py3-none-any.whl.metadata
  Downloading platformdirs-3.10.0-py3-none-any.whl.metadata (11 kB)
Downloading pre_commit-3.3.3-py2.py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.8/202.8 kB 10.5 MB/s eta 0:00:00
Downloading identify-2.5.26-py2.py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.8/98.8 kB 18.7 MB/s eta 0:00:00
Downloading nodeenv-1.8.0-py2.py3-none-any.whl (22 kB)
Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.9/738.9 kB 39.6 MB/s eta 0:00:00
Downloading virtualenv-20.24.2-py3-none-any.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 83.8 MB/s eta 0:00:00
Downloading distlib-0.3.7-py2.py3-none-any.whl (468 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 kB 52.7 MB/s eta 0:00:00
Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
Downloading platformdirs-3.10.0-py3-none-any.whl (17 kB)
Installing collected packages: distlib, pyyaml, platformdirs, nodeenv, identify, filelock, cfgv, virtualenv, pre-commit
Successfully installed cfgv-3.3.1 distlib-0.3.7 filelock-3.12.2 identify-2.5.26 nodeenv-1.8.0 platformdirs-3.10.0 pre-commit-3.3.3 pyyaml-6.0.1 virtualenv-20.24.2

Notice:  A new release of pip is available: 23.0.1 -> 23.2.1
Notice:  To update, run: pip install --upgrade pip
Run pre-commit autoupdate
[https://github.com/pre-commit/pre-commit-hooks] already up to date!
[https://github.com/timothycrosley/isort] already up to date!
[https://github.com/psf/black] updating 23.1.0 -> 23.7.0
[https://github.com/PyCQA/flake8] updating 6.0.0 -> 6.1.0
[https://github.com/pre-commit/mirrors-mypy] updating v1.0.1 -> v1.4.1
[https://github.com/igorshubovych/markdownlint-cli] updating v0.33.0 -> v0.35.0
Run pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/timothycrosley/isort.
[INFO] Initializing environment for https://github.com/timothycrosley/isort:toml.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/PyCQA/flake8:flake8-docstrings.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy:numpy,types-tabulate.
[INFO] Initializing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/timothycrosley/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for merge conflicts................................................Passed
debug statements (python)................................................Passed
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

pyrealm/constants/base.py:52: error: No overload variant of "asdict" matches argument type "ConstantsClass"  [call-overload]
pyrealm/constants/base.py:52: note: Possible overload variants:
pyrealm/constants/base.py:52: note:     def asdict(obj: DataclassInstance) -> dict[str, Any]
pyrealm/constants/base.py:52: note:     def [_T] asdict(obj: DataclassInstance, *, dict_factory: Callable[[list[tuple[str, Any]]], _T]) -> _T
Found 1 error in 1 file (checked 32 source files)

markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

docs/source/users/pmodel/pmodel_details/extreme_values.md:88:[21](https://github.com/ImperialCollegeLondon/pyrealm/actions/runs/5779472488/job/15661796146#step:4:23) MD0[49](https://github.com/ImperialCollegeLondon/pyrealm/actions/runs/5779472488/job/15661796146#step:4:51)/emphasis-style Emphasis style should be consistent [Expected: underscore; Actual: asterisk]

Error: Process completed with exit code 1.

**Comment by davidorme** [comment]
I get this locally after running `pre-commit autoupdate` and then `pre-commit run --all` with the same errors. I think the scheduled CI is running with the updated versions, where the PR jobs are using the existing `.pre-commit.yaml` configuration.
