### ISSUE TITLE
Tests skipped due to broken implementation in rpmodel 1.2.0 (for test_pmodel_global_array)

### ISSUE THREAD

**Issue by a-smith-github** [ImperialCollegeLondon/pyrealm#84]
After investigation this is not a bug, but can we revive this test? 

**Describe the bug**
When running this specific test file, pytest skips the test without failing, citing an issue with rpmodel 1.2.0 (see syndrome below). This is occuring in the GitHub CI but not being flagged.  

**To Reproduce**

poetry run pytest tests/pmodel/test_pmodel_global_array.py -v

Observed on Mac (M2) and in GitHub CI

**Expected behavior**

**Syndrome**

user@machine-name ~/Documents/GitHub/pyrealm % poetry run pytest tests/pmodel/test_pmodel_global_array.py -v
The currently activated Python version 3.11.4 is not supported by the project (>=3.9,<3.11).
Trying to find and use a compatible version.
Using python3.10 (3.10.12)
============================================= test session starts =============================================
platform darwin -- Python 3.10.12, pytest-7.2.0, pluggy-1.0.0 -- /Users/user/Library/Caches/pypoetry/virtualenvs/pyrealm-YqdU8EWB-py3.10/bin/python
cachedir: .pytest_cache
rootdir: /Users/user/Documents/GitHub/pyrealm, configfile: setup.cfg
plugins: mock-3.10.0, flake8-1.1.1, profiling-1.7.0, mypy-0.9.1, cov-3.0.0
collected 5 items

tests/pmodel/test_pmodel_global_array.py::mypy PASSED                                                   [ 20%]
tests/pmodel/test_pmodel_global_array.py::mypy-status PASSED                                            [ 40%]
tests/pmodel/test_pmodel_global_array.py::flake-8::FLAKE8 SKIPPED (file(s) previously passed FLAKE8 checks) [ 60%]
tests/pmodel/test_pmodel_global_array.py::test_pmodel_global_array[ctrl0] SKIPPED (Broken implementation in rpmodel 1.2.0) [ 80%]
tests/pmodel/test_pmodel_global_array.py::test_pmodel_global_array[ctrl1] SKIPPED (Broken implementation in rpmodel 1.2.0) [100%]/Users/as3402/Library/Caches/pypoetry/virtualenvs/pyrealm-YqdU8EWB-py3.10/lib/python3.10/site-packages/coverage/control.py:801: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")

--------- coverage: platform darwin, python 3.10.12-final-0 ----------
Coverage HTML written to dir reports/coverage

==================================================== mypy =====================================================

Success: no issues found in 1 source file
======================================== 2 passed, 3 skipped in 1.11s =========================================

**Desktop (please complete the following information):**

- Mac OS: Ventura 13.2.1 (22D68)
- GitHub CI (Ubuntu, Mac, Windows for Python 3.9 & 3.10) 

**Additional context**

**Comment by davidorme** [comment]
It's tricky. The functionality in `pyyrealm` is diverging from the benchmark implementation using `rpmodel`. I haven't checked recently with updates to `rpmodel` to see if they now align on this test. If they don't,  then we'd need to PR to `rpmodel`.

**Comment by MarionBWeinzierl** [comment]
We can skip the test

**Comment by MarionBWeinzierl** [comment]
There is a comment about this in the source file of the test. It is not a problem in pyrealm, but the external code rpmodel.
